# Generated by Django 4.0.6 on 2022-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('game_type', models.CharField(choices=[('ST', 'Standart'), ('PR', 'Premium')], default='ST', max_length=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
